# This file was generated by the {rix} R package v0.18.2 on 2026-04-19
# with following call:
# >rix(r_ver = "4.5.3",
#  > r_pkgs = c("shiny",
#  > "bsicons",
#  > "dplyr",
#  > "duckdb",
#  > "querychat",
#  > "shinychat",
#  > "random.cdisc.data",
#  > "otelsdk",
#  > "plotly",
#  > "reactable",
#  > "pins"),
#  > git_pkgs = list(package_name = "ellmer",
#  > repo_url = "https://github.com/tidyverse/ellmer",
#  > commit = "35659d1d169c31eaa5908a234ebc3b2b2bc145dd"),
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-04-13.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bsicons
      dplyr
      duckdb
      otelsdk
      pins
      plotly
      querychat
      random_cdisc_data
      reactable
      shiny
      shinychat;
  };
 
    ellmer = (pkgs.rPackages.buildRPackage {
      name = "ellmer";
      src = pkgs.fetchgit {
        url = "https://github.com/tidyverse/ellmer";
        rev = "35659d1d169c31eaa5908a234ebc3b2b2bc145dd";
        sha256 = "sha256-kBwFKyJunbRxD6yHcB4Lyii5JvbMLhtW1mwTxCUoPl8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          coro
          glue
          httr2
          jsonlite
          later
          lifecycle
          promises
          R6
          rlang
          S7
          tibble
          vctrs;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ ellmer rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
